version: 2.1

jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.6.3 
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: cut-api-tests
          RAILS_ENV: test
      - image: circleci/postgres:9.6.7
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: cut-api-tests
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Install correct bundler version
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            gem install bundler
      - restore_cache:
          keys:
            - gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)s
      - store_test_results:
          path: test_results
          